### ISSUE TITLE
Select Same

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#19]
Found an inaccuracy in the Select > Same menu. `minVersion: 26` - but some of the items in this menu are available in earlier versions of Illustrator.

I need time to compare which menu items exist in earlier versions of Illustrator and which were added after CC 2021-2022. For now, I'm opening an issue so that we both don't forget.

**Comment by creold** [comment]
I have attached a list of the commands. In short, only Select > Same > Font / Text has been added in v.26, the previous commands are available with CS6, i.e. they do not need `minVersion`.

[Select.csv](https://github.com/joshbduncan/AiCommandPalette/files/13120488/Select.csv)

**Comment by joshbduncan** [comment]
Oh, this is great! I have it updated and will push a new version release shortly. Thanks again for your help on this!
