### ISSUE TITLE
Command labels

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#2]
Hi, Josh. I found some mistakes in the command labels. Special characters in ExtendScript have to be inserted via Unicode.
![fix-string](https://user-images.githubusercontent.com/32217031/185071345-be98a10a-4a95-458a-9c00-e2c44197b441.jpg)

**Comment by joshbduncan** [comment]
I completely misread your comment the first time. I'm adjusting these now. Thanks again!

**Comment by joshbduncan** [comment]
Fixed in v0.2.2 [ac5b996](https://github.com/joshbduncan/AiCommandPalette/commit/ac5b9964173cc6bbb4182773ed8845cb65f3624a). Please check it out and let me know if you find any more?

**Comment by creold** [comment]
I think English labels are correct now. 👍
