### ISSUE TITLE
Search in Worklfow Builder, Recent Commands

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#20]
Hi Josh. I don't know if this is an isolated bug, but in the Workflow Builder, the search doesn't find Rearrange Artboards. Maybe there are differences between the command lookup in the main window and the Workflow Builder window?
![Search-worklow-builder](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/e4d53648-b36a-4c77-a2a8-933d3793f5f4)

I also see in json `recent:{commands:["config_buildWorkflow","defaults_settings","menu_ReArrange Artboards"]}})`. But when I run the script again, I don't have a list of recent commands. Or am I misunderstanding what recent commands are?
![recent](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/ace4fd55-7a9a-4456-9328-a48c8cd3dcbc)

Version 0.9.0

**Comment by joshbduncan** [comment]
@creold, I recently rebuilt the queryable listbox to include the command type but forgot to update the listbox inside of the workflow builder. I remember trying to build a function that gave me a reusable listbox but failed so I just had to dupe the code in two places and I simply forgot to do it🤦‍♂️. I just push a fix.

As for the "Recent Command". They are under the item "Recent Commands...". I had originally planned to include them in the main startup palette but wasn't sure if people would feel like that was too much. I honestly would prefer them on the first screen so that you don't have the extra step of going to "Recent Commands..." first. What are your thoughts?

Thanks as always for your help! ✌️

**Comment by creold** [comment]
Strange, but Recent Commands... is found only through the search, but by default, when you run the script, this menu is not there 🤔
![recent](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/7a2cb03a-5118-48a1-a577-d5c61e3c74d5)

**Comment by creold** [comment]
"include them in the main startup palette" - give me time to think and I'll try to create a poll in the designers' chat so that they prefer

**Comment by joshbduncan** [comment]
Correct. At the start screen I have `action`, `builtin`, `config`, `menu`, and  `tool` command types hidden from view. My original thought was not to clutter the startup screen so it was easier to access any saved `scripts`, `bookmarks`, and `workflows`. I may be able to hack showing only the "Recent Commands..." builtin. Or I could change the type of "Recent Commands..." to `defaults` which would make it visible at startup...

**Comment by creold** [comment]
Maybe so? Recent commands, if they exist, are always displayed above Settings. And the favorites are above these two items
![recent](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/2d99565c-0c21-4889-b798-8fe29ebc2af6)

**Comment by creold** [comment]
When using the Ai Command Palette, I instinctively want to press the up key when the first line of the list is selected, so that the selection moves to the last line of the list =) That is, scrolling in a loop, without stopping at the first and last item. But then it looks like we'll need a custom event handler that checks the UP key code and that the first line is now selected.

**Comment by joshbduncan** [comment]
Yes, I have plans to allow the startup screen to be configurable by the user but for now, I agree that adding the `Recent Commands...` item to the startup menu if a good idea.

On the hitting up to go to the bottom of the list, I do the same thing many times a day 🤦‍♂️. I know I have thought of adding a little sub-routine to do that but I never put in into [TODO.md](https://github.com/joshbduncan/AiCommandPalette/blob/main/TODO.md). I may try and tackle that tomorrow, if I can find a few free minutes.

Thanks again for your ideas and help!

**Comment by creold** [comment]
My experiment with the event handler
```
var w = new Window ("dialog");
w.alignChildren = "fill";
w.preferredSize.width = 200;
var list = ["one", "owo", "three", "four", "five"];
var listBox = w.add("listbox", undefined, list);

scrollList(listBox, list.length - 1);

function scrollList(obj, last) {
  obj.addEventListener("keydown", function (kd) {
    if (kd.keyName == "Up" && obj.selection.index == 0) {
      obj.selection = [last];
      kd.preventDefault();
    }
    if (kd.keyName == "Down" && obj.selection.index == last) {
      obj.selection = [0];
      kd.preventDefault();
    }
  });
}

w.show ();
```
![2023-11-10 10 39 55](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/b58e03af-f4d3-4449-b047-2189af38507a)

I wanted to use the `true` or `false` check for `Scripting.environment.KeyboardState.shiftKey` to increment 10 or 1 to scroll, but it didn't work.

**Comment by joshbduncan** [comment]
Yep, that's exactly how I would go about it as well. With the command palette, it's going to be a little more tricky. Since you can use the arrow key from with the search box to I have to do some magic to keep the proper list items in view once there are more items in the list than can be viewed at once. It should be too hard to implement in a similar fashion as you have done. Thanks for your help!

**Comment by joshbduncan** [comment]
@creold, I've got the end-to-end scrolling implemented. I implemented it to work from within the query input and within the actual list (using your code). Take it for a spin and let me know what you think. Cheers!

**Comment by creold** [comment]
@joshbduncan of course, it has become more convenient to go to the last items of the lists. Hooray! What do you think about adding "Recent commands" in front of the settings? Any plans for future releases?

**Comment by joshbduncan** [comment]
I'm a goof 🤪, I completely forgot about adding the recent commands to the start-up screen. I'll get that fixed and a new update out soon. Other than that, the only thing I hoped to work on next would be to make a start-up screen customizer. The plan is something like the workflow builder but for customizing the start-up screen. That way you could have exactly the commands you want shown when you open the command palette.

**Comment by creold** [comment]
By the way, have you noticed that when the search results do not fit into a viewport, the list flickers when you press the keyboard arrows? It's as if another item is selected first, and then the one you switched to from the keyboard. If the command list occupies a viewport, there is no such flickering.

**Comment by joshbduncan** [comment]
@creold, I think issue #21 is what you were referring to this morning. [See my post here](https://github.com/joshbduncan/AiCommandPalette/issues/21#issuecomment-1815178956) and let me know what you think is the best approach.

**Comment by joshbduncan** [comment]
@creold, until I can get the time to build a start-up screen builder/customizer, I just moved the `Recent Commands` command to the `defaults` category so that it shows up on startup.
