### ISSUE TITLE
Pressing arrows makes the list blink

### ISSUE THREAD

**Issue by gchegr** [joshbduncan/AiCommandPalette#21]
When using arrow keys to navigate the list of results, the list blinks.
Closer analysis reveals the list gets scrolled into a state when the selected item becomes the first one in the frame and instantly restores.
Take a look at the GIF attached, please.
![blink_focus_2](https://github.com/joshbduncan/AiCommandPalette/assets/81404846/42bdc887-52fe-4d2f-b211-22cf2e2bd7b5)

**Comment by gchegr** [comment]
Aha, the script has this behavior documented... I assume then it can’t be fixed :( ...or can it?

**Comment by joshbduncan** [comment]
Yeah, this drives me crazy every day. So, while you are in the query/search box and hit the arrow up or down arrow key, if I simply move the selection up/down the selected item is always at the top. This means you can see what options are above your current option. If you go too far down, for example, you can't really see how far to go back up. This is also counter to how the listbox operates when you are inside of it and not inside the query/search box.

As you can see in the video, at first I am hitting the arrow keys from within the search box and the selection is staying at the top but in the second part of the video when I actually make a selection in the listbox and hit the arrow keys, the "viewport" of list items doesn't change until I get to the bottom or top. My solution was to track that "viewport" and move it around to try and mimic how the listbox works when it is selected. Unfortunately, that leads to the flickering. What is actually happening is that when I select the next item (up or down) it immediately jumps to the top, then I shift the viewport around to mimic the behavior I described and sometimes when this process happens slowly (usually when going up and down fast), you can see the flicker.

I've tried a handful of hacks to get around this but I couldn't figure anything else out...

What is your opinion of the best solution? Just let the selected item stay at the top or move the viewport around but have the flicker?

https://github.com/joshbduncan/AiCommandPalette/assets/44387852/c2f6ca19-bc2e-4b28-b44b-0a92d1195939

**Comment by creold** [comment]
I found a keyboard life hack for Mac OS. 
1) Type a search query, 
2) press Shift + Tab to activate the list and scroll without flickering, 
3) press Tab to return to the search field. 

@gchegr told me that on a PC, Shift+Tab activates bottom buttons, but not a list.

https://github.com/joshbduncan/AiCommandPalette/assets/32217031/7e1384c9-5314-4dba-8526-11a4fa12e6aa

**Comment by joshbduncan** [comment]
Yeah, I know that works but it's not ideal IMHO... All of the command palettes I use from other apps allow you to navigate the option right from the search box. I have another idea that I'll text tomorrow but unfortunately this may be one of those situations without a good fix.

**Comment by gchegr** [comment]
It’s better to have the proper behavior, even if it causes flickering.
For those who can’t stand it — well, a flag one can toggle in the code.

I wonder also if anything can be done to solve this —
![image](https://github.com/joshbduncan/AiCommandPalette/assets/81404846/33cd4f0f-4fab-4aef-8f49-3651e99291e7)
I can’t resize the panel to make the list to have the items not trimmed (which I can log as a separate issue).

**Comment by joshbduncan** [comment]
It seems windows draws the rows a little taller than Mac OS does. I set the size based of my Mac and it perfectly fits 9 rows. I can adjust the sizes depending on the operating system. I don't have a windows machine so if it's okay, I'll send you a sample JSX file to test the size and make sure it is perfect.

**Comment by gchegr** [comment]
Sure, please do, I’d be ready to help.
How can I DM you here? Have no idea.
It looks like GitHub does not allow to specify email as a contact.

**Comment by joshbduncan** [comment]
So, I think I've hit a dead end on this and I don't think there is a good fix/hack. With that said, my plan is to leave the flicker as the default functionality but allow users to press the SHIFT key while using the up and down arrows to navigate through the list without the flicker (but the selected item always at the top). I'll note this in the README too.

As for the sizing, I'm going to make another issue so I don't forget. You can reach me directly at XXXX if that is easier.

**Comment by joshbduncan** [comment]
@gchegr  and @creold, I have completely rewritten the code for the arrow functionality. By default, it will act as before with proper behavior but with the weird blinking bug. If you hold shift down while pressing the arrow keys (all while in the query box) the selected item will stay at the top but there will be no flickering. New code isn't officially released yet but can be download in the [v0.10.0 brach](https://github.com/joshbduncan/AiCommandPalette/commit/ce4c6070f0acb24fc5bb851dcd50a4ec5e8c14e6). Cheers!
