### ISSUE TITLE
fuzzy searching

### ISSUE THREAD

**Issue by joshbduncan** [joshbduncan/AiCommandPalette#26]
Requested by [@RasmusMalver](https://github.com/RasmusMalver)

**Comment by joshbduncan** [comment]
# A little background...

Currently, on any change to the query/search box, the script iterates over every command supplied to the command palette (see note below) and scores each command in relation to the query based on the following rules...

> Note: Not all command palettes are equal. Some have access to every possible command and some only have access to a limited set of commands e.g. 'Palette Settings and Configuration'.

# Current Positives

- really fast results when typing and especially backspacing within the query/search input
- easy to narrow down results using parents menus in query (e.g. 'file export' query will show every command available in the 'File > Export' menu if you can't remember the exact command name
- easy to implement using built-in ExtendScript (ES3)

## Current Issues

- queries without proper spacing don't match (e.g. 'newt' for 'File > New from Template...', 'exa' for 'File > Export > Export As...', 'outstr' for 'Object > Path > Outline Stroke')
- abbreviated queries (e.g. 'ol sr' for 'Object > Path > Outline Stroke')
- queries with misspellings (especially in the first few letters) or transposed letters

## Scoring Rules

1. check for exact matches of command name (rare)
2. check for exact matches of command type if 'Enable Searching on Command Type' is enabled
3. remove unneeded characters (e.g. '>' and '...') from the current command name
4. split the query into individual words
5. check if any of the individual query words matches the beginning of any word in the command string using a regular expression (the command string includes the full menu path as well as the command name e.g. 'Object > Align > Horizontal Align Left')
6. for each match, increase the command score by the length of the matching word
7. if a command has a score <= 0, ignore
8. if the exact query and command combination can be found in the command history (keyword/query latching), increase it's score by a lot (allows for quickly accessing often used commands)
9. if the command was run recently but with a different query, increase it's score by a little
10. sort the scoring commands in descending order by their score

**Comment by joshbduncan** [comment]
I just pushed a new commit to the 'fuzzy' branch that implements a much better fuzzy search algorithm based on John Hawthorn's [fzy](https://github.com/jhawthorn/fzy)...

It should provide much better results for searches like 'exa' and 'newt' (mentioned in the above [comment](https://github.com/joshbduncan/AiCommandPalette/issues/26#issuecomment-2007875708)).

The fuzzy matching process is definitely slower when returning matches than the current implementation. It is especially noticeable when typing very fast or backspacing/deleting characters rapidly. I tried, caching some of the info to speed things up, but I didn't really help 🤷‍♂️.

**Comment by RasmusMalver** [comment]
> The fuzzy matching process is definitely slower when returning matches than the current implementation. It is especially noticeable when typing very fast or backspacing/deleting characters rapidly. I tried, caching some of the info to speed things up, but I didn't really help 🤷‍♂️.

Yeah, definately slower. Now that I know that fuzzy matching is available with spaces, maybe I should just learn to do it that way 🙂

**Comment by leeoniya** [comment]
shameless plug: https://github.com/leeoniya/uFuzzy

you can compare here: https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,fzy&search=super%20ma

**Comment by joshbduncan** [comment]
@RasmusMalver, I am going to try one more thing. I think I can make the original implementation also work "fuzzy" style with queries like 'exa' and 'newt'. I'm pretty sure you are not the only person searching that way. I'll let you know if I can get it to work. Cheers!

**Comment by joshbduncan** [comment]
@leeoniya, I'm sure your fuzzy library is much better than what I hacked together... Unfortunately, I have play within the confines of ExtendScript which is an ES3 version of JavaScript for Adobe scripting. I am pretty sure not matter the fuzzy algo, I use, it will be slow inside of ExtendScript. Thanks for the heads up!

**Comment by joshbduncan** [comment]
@RasmusMalver, I think I have an acceptable solution (commit [7578608](https://github.com/joshbduncan/AiCommandPalette/commit/7578608886ab1d484ee4b6e962e21f9e9dcb8185)) on the 'fuzzy' branch. It works with queries like "oust", "ou st", and "st ou" for "outline stroke". Not only does the algo match the beginning of words (bonus points) but also interior letters. I loosely modeled this after the amazing [fzf](https://github.com/junegunn/fzf) fuzzy finder cli tool.

If your query has spaces, each chunk is searched for independently, and this helps in the case of "st ou", where you want "outline stroke" but get the words out of order.

The algo, still adds bonus points for the keyword-latching feature, recent commands, and command type matching (if enabled). Bonus points are also added if the matched characters are after the last carrot ">" when dealing with menu items.

Speed is not as fast, especially when backspacing characters quickly, but it is pretty good and acceptable (I think)...

Take it for a if you have time and let me know what you think. Thanks!

**Comment by joshbduncan** [comment]
Just pushed what will probably be the final commit before doing a PR. Added query caching to speed up the lag when backspacing, added more bonus points for whole-word matches and removed searching on type (added built-in commands instead).
