### ISSUE TITLE
New localization

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#3]
Following Kurt Gold, I did a complete localization for the Russian app language. In English "...Tool" (e.g. Arc Tool) is at the end of the labels, in Russian I put "Инструмент:" at the beginning of labels.

[Russian.csv](https://github.com/joshbduncan/AiCommandPalette/files/9357836/Russian.csv)

**Comment by joshbduncan** [comment]
Wow, this is great! I'll get this translated and push up today as well. Nice work! Thanks! 👍

**Comment by joshbduncan** [comment]
Added in v0.2.2 [ac5b996](https://github.com/joshbduncan/AiCommandPalette/commit/ac5b9964173cc6bbb4182773ed8845cb65f3624a). The Russian version seems to runs fine on my system but I obviously can't read the items so please check it out and let me know if everything looks good. Thanks again @creold!

**Comment by creold** [comment]
I corrected three lines of the Russian localization:
n55: `Reveal Hidden Commands?\n`
n81: `File > New from Template...`
n574: `Preferences > Appearance of Black...`
[Russian_v2.csv](https://github.com/joshbduncan/AiCommandPalette/files/9365520/Russian_v2.csv)

In the English version 0.2.2, all labels seem to be correct. Russian localization works fine.

P.S. In Readme.md `- [@creold]` without link :-) You can copy as my name `- [Sergey Osokin](https://github.com/creold)`

**Comment by joshbduncan** [comment]
Ok, I'll get these updated and get your name correct. I thought I could just tag you on GitHub but that didn't work. Also, I just pushed [v0.2.3 - b040ad5](https://github.com/joshbduncan/AiCommandPalette/commit/b040ad5b98e07a4c0cd72f5127db3467e9b4bf1d) which includes some enhancements to the workflow builder suggested by Kurt Gold. Thanks!

**Comment by joshbduncan** [comment]
@creold I got your updates pushed in the latest commit [98d80ab](https://github.com/joshbduncan/AiCommandPalette/commit/98d80aba832d858824babb1c8c20a5b0d8929e14). I also got your name updated correctly in the README. Thanks again for helping on this.

**Comment by creold** [comment]
Awesome
