### ISSUE TITLE
Error 25

### ISSUE THREAD

**Issue by marrtw** [joshbduncan/AiCommandPalette#31]
Hi,

I just installed the script and get the error below when I run the script. BTW, this script looks amazing (watched your video).

![image](https://github.com/user-attachments/assets/64de220e-4413-4a40-b821-a21fd3bda058)

**Comment by marrtw** [comment]
I should probably note that I'm on Illustrator version 29.1.

**Comment by joshbduncan** [comment]
Hey @marrtw, it looks like you download the wrong thing from GitHub and not the actual script. [Go here](https://github.com/joshbduncan/AiCommandPalette/blob/main/AiCommandPalette.jsx) and click the "Download raw file" button (see screenshot). Load, the .jsx file that download into Ai and you should be to go. Cheers!

![CleanShot 2024-12-26 at 14 45 16@2x](https://github.com/user-attachments/assets/5e9a8206-c76b-433a-9045-3335b73a910e)

**Comment by marrtw** [comment]
Thanks so much for getting back to me. 

 

I did download the AiCommandPalette.jsx file originally. When it didn’t work, as an experiment, I asked ChatGPT if it could help me determine the problem. It came back with an answer (which I couldn't understand as I’m not a programmer, but something about polygons) and offered to fix the problem. I’d paste the response it gave but ChatGPT is having technical issues at the moment and the history of our conversation isn’t available. Anyway, I saved the new code to the same file and it seems to work perfectly now.

 

Thanks for making this script available. It looks fantastic.

 

Tom

**Comment by joshbduncan** [comment]
Yeah, I think you may have actually downloaded part of the GitHub webpage... No worries though. Glad you got it up and running. Let me know if you have any questions, issues, or ideas on improvements/additions. Cheers!

**Comment by marrtw** [comment]
ChatGPT finally got history working again. I’ve pasted below what it said about the error. I thought you might be curious. 

 

I noticed the script is quite lengthy. Let me quickly identify the issue on line 42 and suggest a fix. Hang on.

The code around line 42 seems to be part of a polyfill implementation for Array.prototype.includes. Here is the relevant snippet:

javascript

Copy code

    start = 0;

  }

  return this.indexOf(search, start) !== -1;

};

The error "Error 25" often points to a syntax issue or misinterpretation by Adobe Illustrator's scripting engine. Let me analyze this further and suggest a fix. ​​

The issue seems to arise from this part of the polyfill for Array.prototype.includes:

javascript

Copy code

if (!Array.prototype.includes) {

  Array.prototype.includes = function (search, start) {

    if (start === undefined) {

      start = 0;

    }

    return this.indexOf(search, start) !== -1;

  };

}

This code looks syntactically correct, but Adobe Illustrator's ExtendScript engine sometimes has quirks interpreting JavaScript, particularly with modern ES6+ methods or missing explicit type handling.

Potential Fixes:

1.	Ensure ExtendScript Compatibility: Modify the start assignment to be more explicit about its type:

javascript

Copy code

if (typeof start === "undefined" || start === null) {

    start = 0;

}

2.	Use Alternative Logic: If compatibility remains an issue, you can replace .includes entirely with a simpler indexOf implementation:

javascript

Copy code

if (!Array.prototype.includes) {

  Array.prototype.includes = function (search, start) {

    start = start || 0; // Default to 0 if start is undefined or null

    return this.indexOf(search, start) !== -1;

  };

}

Let me know if you'd like me to rewrite the affected part of the script and provide the updated code.

**Comment by joshbduncan** [comment]
Hey, sorry I think you are misunderstanding me. The error you initially got was because you download something other than my script. It seems you may have downloaded some part of the GitHub website. If you look at the image you initially posted, you can see it is Javascript code that hints to some GitHub/Microsoft services. So the error you are getting has nothing to do with my script. That's why the ChatGPT says "This code looks syntactically correct"... Let me know if this makes sense?

![image](https://github.com/user-attachments/assets/0ac08e5d-4e11-4fc3-9d70-024a10145d91)

**Comment by marrtw** [comment]
Hey Josh,

 

This is really weird. You are right though.  I looked at the original file and there’s some odd stuff in there. I use a download manager (IDM) and this could be the cause I guess. However, I’ve never had a problem with any other file in the 25+ years I’ve used this download manager…which I originally installed when using a dialup connection, possibly before you were even born. 😊 Thanks for clearing this up. 

 

Tom

**Comment by joshbduncan** [comment]
Haha, I wish I was that young! About to turn 43 in a few months so I know all too well about dial-up Internet. I spent most of my teenage years listening to those wonderful modem noises 🙉... Although, I have never heard of IDM which surprises me. Glad, everything is working for you now. I hope you have a great new year!
